# Generated by Django 4.2.1 on 2023-05-15 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_shift_shiftapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='hospital', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='nurse', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
