from core.testcases.jwt_authentication_tests import JwtAuthenticationTests
from core.testcases.profile_tests import ProfileTest
from core.testcases.shift_tests import ShiftTest
from core.testcases.shift_application_tests import ShiftApplicationTest